set(TARGET llama-rknpu-prepack)
add_executable(${TARGET} rknpu-prepack.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE llama ggml ${CMAKE_THREAD_LIBS_INIT})
target_include_directories(${TARGET} PRIVATE ../../ggml/src/ggml-rknpu_re)
target_compile_features(${TARGET} PRIVATE cxx_std_17)
