set(TARGET llama-rknpu-host-reload)
add_executable(${TARGET} rknpu-host-reload.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE ggml ggml-rknpu-re ${CMAKE_THREAD_LIBS_INIT})
target_include_directories(${TARGET} PRIVATE ../../ggml/src/ggml-rknpu_re)
target_compile_features(${TARGET} PRIVATE cxx_std_17)
